### ISSUE TITLE
The mock backend behind HADWIN is unavailable HTTP status code 503.

### ISSUE THREAD

**Issue by sanasz91mdev** [brownboycodes/HADWIN#11]
Hi, i want to try the app but i cant login or sign up. The mock backend behind HADWIN is unavailable status code 503.

**Comment by brownboycodes** [comment]
Hi @sanasz91mdev  thank you for reporting this. looking into it

**Comment by brownboycodes** [comment]
it is going to take some time as it appears that heroku has terminated free dynos plans and I am left with no other choice than to switch to some other hosting service.

**Comment by sanasz91mdev** [comment]
> it is going to take some time as it appears that heroku has terminated free dynos plans and I am left with no other choice than to switch to some other hosting service.

No problem. your app design is truly very minimalistic and classic

**Comment by brownboycodes** [comment]
@sanasz91mdev that credit should go to the ux designers please do check out their work

**Comment by sanasz91mdev** [comment]
> @sanasz91mdev that credit should go to the ux designers please do check out their work

any link to that?

**Comment by brownboycodes** [comment]
@sanasz91mdev https://github.com/brownboycodes/HADWIN#credits-

**Comment by brownboycodes** [comment]
The backend earlier deployed on [Heroku](https://blog.heroku.com/next-chapter) has been redeployed to [Render](https://render.com/).
services will be restored as soon all old api endpoints gets replaced with new ones

**Comment by brownboycodes** [comment]
@sanasz91mdev the issue has been fixed. 
thank you for bringing to my notice
